### ISSUE TITLE
Recurrent Layer Attributes are not Correct

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge-keras#118]
In `deepforge-keras`, some recurrent nodes have some properties that are not correct. Specifically, when you look at something like GRU in the meta viewer. 
![META](https://user-images.githubusercontent.com/11476842/65183459-232a4d80-da29-11e9-918b-d5c1a9437685.png)

It should not be the case that the attributes like `kernel_constraint`, `recurrent_activation`, `recurrent_constraint`, `recurrent_dropout` etc... be of type string. Some of them should be `pointers` to the original layer node. 

Nodes showing this behavior: `LSTM`, `GRU` , `RNN` and more to be tested.

Probable cause of this issue:
- Most likely caused because of the key `type` missing in the layer schema that is generated by the [layer-parser](https://github.com/deepforge-dev/deepforge-keras/blob/master/src/common/layer-parser.js) of `deepforge-keras`.

**Comment by brollb** [comment]
It appears that there are actually many more with the same type of errors:
![DeepinScreenshot_xterm_20191106105756](https://user-images.githubusercontent.com/4982789/68319716-5e89e580-0084-11ea-9e2a-f5aa7c8b3d59.png)
