### ISSUE TITLE
Add tests ensuring the output of GenerateKeras is valid keras code

### ISSUE THREAD

**Issue by brollb** [deepforge-dev/deepforge-keras#126]
It would be good to add more tests ensuring that the output of GenerateKeras can actually be executed. That is, we should add tests which run the generated code in a python interpreter.

This will require some updates to the CI setup (travis.yml)

**Comment by brollb** [comment]
This would also be helpful for testing the code import.

**Comment by umesh-timalsina** [comment]
I will dig into this, adding relavent changes to CI, as well as the plugin itself.
