### ISSUE TITLE
Lists cannot be used as input shapes in ArchEditor

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge-keras#135]
![image](https://user-images.githubusercontent.com/11476842/68413482-f571a300-0153-11ea-8fae-5d56ae82459a.png)

Whenever you want to use a list as a tensorshape in `KerasArchEditor`, you will get a message saying Error converting shape to a tensorshape(as shown in the screenshot).

This issue is resolved if you use tuples `( dim1, dim2, ... dimn)` with the Layer.

**Comment by brollb** [comment]
This was fixed by #125
