### ISSUE TITLE
Update deepforge-extension.json to include python dependencies

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge-keras#163]
We should include python dependencies (along with preferred installer (conda, pip), any channels to be added etc..) in the deepforge-extension.json.

**Comment by brollb** [comment]
If we are centering around conda (https://github.com/deepforge-dev/deepforge/issues/1402), it might make more sense to use conda environment files rather than specifying all these things in our own way (reinventing the wheel).

**Comment by brollb** [comment]
This is blocked by the method of specifying dependencies in deepforge: https://github.com/deepforge-dev/deepforge/issues/1466
