### ISSUE TITLE
Graph neural network support

### ISSUE THREAD

**Issue by brollb** [deepforge-dev/deepforge-keras#213]
It might be nice to add support for graph neural networks. One option would be to use [spektral](https://github.com/danielegrattarola/spektral) as it includes custom layers for graph convolution, attention layers, etc.

**Comment by umesh-timalsina** [comment]
Nice idea, are there any standard benchmarks for Graph Neural Networks? Like `cifar10` or `mnist` for images?

**Comment by brollb** [comment]
Yeah, there are a few like [Open Graph Benchmark](https://ogb.stanford.edu/). There are actually a few examples in spektral that are already using benchmark datasets (available in the library as well). They are pretty nice and reference the origin papers (like [here](https://github.com/danielegrattarola/spektral/blob/master/examples/node_prediction/citation_gat.py#L1-L6)).
