### ISSUE TITLE
Refactor JSONImporter to a separate Repository?

### ISSUE THREAD

**Issue by umesh-timalsina** [deepforge-dev/deepforge-keras#223]
It might be nice to refactor [`JSONImporter`](https://github.com/deepforge-dev/deepforge-keras/blob/v2.0.0/src/common/plugins/JSONImporter.js) to a separate repository, this will be helpful for writing model transformations, creating metamodels and many more things for `webgme`.

**Comment by brollb** [comment]
I agree. Currently, it is just copied out when used in other projects (like @wscrosswy); of course, this certainly isn't ideal as it would be good to move it to a repo within deepforge-dev.

I have also been wondering if there would be a better name for it but not sure what it should be...
