### ISSUE TITLE
Export architectures to JSON

### ISSUE THREAD

**Issue by brollb** [deepforge-dev/deepforge-keras#52]
It might be useful to generate JSON from the model...

**Comment by umesh-timalsina** [comment]
As per @brollb's suggestion.
- subclass [GenerateKeras](https://github.com/deepforge-dev/deepforge-keras/tree/master/src/plugins/GenerateKeras) and use it to generate the standard code
- add a line which prints the model json
- pass the code to python in a subprocess (async this time)
- return the stdout (json printout) to the user as a file
